apiVersion: v1
kind: Service
metadata:
  name: devops-azure-api-nodeport
  labels:
    app: devops-azure-api
spec:
  type: NodePort
  selector:
    app: devops-azure-api
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
